import React from 'react';
import { useInvestigation } from '../context/InvestigationContext';
import {
  Download,
  Printer,
  ChevronLeft,
  Ship,
  Satellite,
  Compass,
  ListOrdered,
} from 'lucide-react';
import { DEMO_INVESTIGATION_DOSSIER } from '../data/demoData';

export const ReportPage: React.FC = () => {
  const {
    currentCase,
    suspects,
    goToRoute,
  } = useInvestigation();

  const topSuspect = suspects[0];

  const handleExportJson = () => {
    const reportData = {
      caseId: currentCase.id,
      generatedAt: new Date().toISOString(),
      disclaimer:
        'Model-based attribution is probabilistic. Analytical inference generated by research pipeline.',
      dossier: DEMO_INVESTIGATION_DOSSIER,
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${currentCase.id}-investigation-report.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleExportCsv = () => {
    const headers = [
      'Rank',
      'VesselName',
      'MMSI',
      'VesselType',
      'ClosestApproachKm',
      'ClosestHourBack',
      'TimeClosestApproach',
      'CourseDeg',
      'SpeedKn',
      'TimeMatchPct',
      'CulpritScorePct',
    ];

    const rows = suspects.map((s) => [
      s.rank,
      `"${s.vesselName}"`,
      s.mmsi,
      `"${s.vesselType}"`,
      s.mdoKm,
      `"T-${s.closestHourBack}h"`,
      `"${s.timeClosestApproach}"`,
      s.cogDeg,
      s.sogKn,
      s.timeMatchPct,
      s.culpritScorePct,
    ]);

    const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${currentCase.id}-candidate-vessels.csv`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="flex-1 overflow-y-auto bg-[#091524] text-[#edf4fd] font-sans py-8 px-4 sm:px-8 select-none">
      <div className="max-w-3xl mx-auto space-y-8">
        {/* Top Actions Bar */}
        <div className="flex items-center justify-between border-b border-[#1168a0]/40 pb-4 print:hidden">
          <button
            onClick={() => goToRoute('investigation')}
            className="flex items-center gap-1.5 text-xs text-[#89bada] hover:text-[#edf4fd] font-semibold transition-colors cursor-pointer"
          >
            <ChevronLeft className="w-4 h-4" />
            <span>Return to Workspace</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={handleExportJson}
              className="px-3.5 py-1.5 rounded-lg bg-[#082e49] hover:bg-[#1168a0] border border-[#1168a0]/80 text-xs text-[#edf4fd] flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs"
            >
              <Download className="w-3.5 h-3.5 text-[#89bada]" />
              <span>Export JSON</span>
            </button>

            <button
              onClick={handleExportCsv}
              className="px-3.5 py-1.5 rounded-lg bg-[#082e49] hover:bg-[#1168a0] border border-[#1168a0]/80 text-xs text-[#edf4fd] flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs"
            >
              <Download className="w-3.5 h-3.5 text-[#89bada]" />
              <span>Export CSV</span>
            </button>

            <button
              onClick={handlePrint}
              className="px-3.5 py-1.5 rounded-lg bg-[#f1aa6f] hover:bg-[#f4b680] text-[#0a3554] font-bold text-xs flex items-center gap-1.5 transition-colors cursor-pointer shadow-md shadow-[#f1aa6f]/20"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Report</span>
            </button>
          </div>
        </div>

        {/* Clean Report Document Container */}
        <div className="bg-[#0a1829] border border-[#1168a0]/60 rounded-2xl p-8 sm:p-12 shadow-2xl space-y-8 print:border-none print:shadow-none print:p-0 print:bg-transparent text-[#edf4fd]">
          {/* Header */}
          <div className="border-b border-[#1168a0]/50 pb-6 flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4">
            <div>
              <div className="text-[11px] text-[#f1aa6f] tracking-wider font-bold mb-1">
                MARINE SPILL INTELLIGENCE DOSSIER
              </div>
              <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
                Investigation Report
              </h1>
              <p className="text-xs text-[#89bada] mt-1">
                Satellite SAR Detection & Reverse-Lagrangian Attribution Pipeline
              </p>
            </div>

            <div className="text-left sm:text-right">
              <span className="text-[10px] text-[#89bada] block uppercase font-semibold">CASE IDENTIFIER</span>
              <span className="text-lg font-extrabold text-[#f1aa6f] tracking-wider">
                {currentCase.id}
              </span>
            </div>
          </div>

          {/* Section 1: Observation */}
          <div className="space-y-2">
            <h2 className="text-xs font-bold text-[#89bada] uppercase tracking-wider flex items-center gap-2 border-b border-[#1168a0]/40 pb-1.5">
              <Satellite className="w-3.5 h-3.5 text-[#f1aa6f]" />
              <span>OBSERVATION</span>
            </h2>
            <p className="text-xs text-[#edf4fd]/90 leading-relaxed">
              Satellite SAR observation detected an elongated radar-dark anomaly in international shipping lanes within the Ionian Sea, Mediterranean Basin. Radiometric profiling indicates significant capillary wave damping consistent with mineral petroleum hydrocarbon release.
            </p>
          </div>

          {/* Section 2: Slick Characterisation */}
          <div className="space-y-3">
            <h2 className="text-xs font-bold text-[#89bada] uppercase tracking-wider flex items-center gap-2 border-b border-[#1168a0]/40 pb-1.5">
              <span>SLICK CHARACTERISATION</span>
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div className="p-3.5 bg-[#082e49]/90 rounded-xl border border-[#1168a0]/60">
                <span className="text-[10px] text-[#89bada] block font-medium">Area</span>
                <span className="text-sm font-bold text-white">17.73 km²</span>
              </div>
              <div className="p-3.5 bg-[#082e49]/90 rounded-xl border border-[#1168a0]/60">
                <span className="text-[10px] text-[#89bada] block font-medium">Capture</span>
                <span className="text-xs font-bold text-white">26 Oct 2019 • 05:53 UTC</span>
              </div>
              <div className="p-3.5 bg-[#082e49]/90 rounded-xl border border-[#1168a0]/60">
                <span className="text-[10px] text-[#89bada] block font-medium">Centroid</span>
                <span className="text-xs font-bold text-white">35.5240° N, 18.4520° E</span>
              </div>
              <div className="p-3.5 bg-[#082e49]/90 rounded-xl border border-[#1168a0]/60">
                <span className="text-[10px] text-[#89bada] block font-medium">Substance Type</span>
                <span className="text-xs font-bold text-[#f1aa6f]">Heavy Fuel / Sludge</span>
              </div>
            </div>
          </div>

          {/* Section 3: Reconstruction */}
          <div className="space-y-3">
            <h2 className="text-xs font-bold text-[#89bada] uppercase tracking-wider flex items-center gap-2 border-b border-[#1168a0]/40 pb-1.5">
              <Compass className="w-3.5 h-3.5 text-[#f1aa6f]" />
              <span>RECONSTRUCTION</span>
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
              <div className="p-3.5 bg-[#082e49]/90 rounded-xl border border-[#1168a0]/60">
                <span className="text-[10px] text-[#89bada] block font-medium">Hindcast window</span>
                <span className="text-sm font-bold text-white">24 hours</span>
              </div>
              <div className="p-3.5 bg-[#082e49]/90 rounded-xl border border-[#1168a0]/60">
                <span className="text-[10px] text-[#89bada] block font-medium">Particles</span>
                <span className="text-sm font-bold text-white">1,750</span>
              </div>
              <div className="p-3.5 bg-[#082e49]/90 rounded-xl border border-[#1168a0]/60">
                <span className="text-[10px] text-[#89bada] block font-medium">KDE Envelope</span>
                <span className="text-sm font-bold text-[#89bada]">95% Confidence</span>
              </div>
              <div className="p-3.5 bg-[#082e49]/90 rounded-xl border border-[#1168a0]/60">
                <span className="text-[10px] text-[#89bada] block font-medium">Forcing Datasets</span>
                <span className="text-xs font-bold text-[#edf4fd]">ERA5 + CMEMS</span>
              </div>
            </div>
            <p className="text-xs text-[#edf4fd]/90 leading-relaxed">
              Estimated release origin reconstructed to <strong className="text-[#f1aa6f]">35.4821° N, 18.3914° E</strong> at <strong className="text-white">T−16h (25 Oct 2019 13:53 UTC)</strong>, encompassing an envelope area of 8.42 km² along the primary shipping traffic corridor.
            </p>
          </div>

          {/* Section 4: AIS Correlation */}
          <div className="space-y-3">
            <h2 className="text-xs font-bold text-[#89bada] uppercase tracking-wider flex items-center gap-2 border-b border-[#1168a0]/40 pb-1.5">
              <Ship className="w-3.5 h-3.5 text-[#f1aa6f]" />
              <span>AIS CORRELATION</span>
            </h2>
            <div className="flex items-center gap-3 text-xs text-[#edf4fd]">
              <div className="p-3.5 bg-[#082e49]/90 rounded-xl border border-[#1168a0]/60 flex-1">
                <span className="text-[10px] text-[#89bada] block font-medium">Screened AIS Traffic</span>
                <span className="text-sm font-bold text-white">28 vessels screened</span>
              </div>
              <div className="p-3.5 bg-[#082e49]/90 rounded-xl border border-[#1168a0]/60 flex-1">
                <span className="text-[10px] text-[#89bada] block font-medium">Identified Candidates</span>
                <span className="text-sm font-bold text-[#f1aa6f]">5 candidates identified</span>
              </div>
            </div>
          </div>

          {/* Section 5: Candidate Vessel */}
          <div className="space-y-3.5 p-6 rounded-2xl bg-[#082e49]/90 border border-[#1168a0] shadow-xl">
            <div className="flex items-center justify-between border-b border-[#1168a0]/50 pb-3">
              <span className="text-xs font-bold text-[#89bada] tracking-wider uppercase">
                PRIMARY CANDIDATE VESSEL
              </span>
              <span className="px-3 py-1 rounded-full bg-[#f1aa6f] text-[#0a3554] text-xs font-black shadow-md">
                SCORE: {topSuspect.culpritScorePct}%
              </span>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs">
              <div>
                <span className="text-[#89bada] block text-[10px] font-medium">Vessel Name</span>
                <span className="text-sm font-extrabold text-white">{topSuspect.vesselName}</span>
              </div>
              <div>
                <span className="text-[#89bada] block text-[10px] font-medium">MMSI</span>
                <span className="text-sm font-bold text-[#89bada]">{topSuspect.mmsi}</span>
              </div>
              <div>
                <span className="text-[#89bada] block text-[10px] font-medium">Vessel Type</span>
                <span className="font-semibold text-[#edf4fd]">{topSuspect.vesselType}</span>
              </div>
              <div>
                <span className="text-[#89bada] block text-[10px] font-medium">Closest approach</span>
                <span className="text-sm font-bold text-[#f1aa6f]">{topSuspect.mdoKm} km</span>
              </div>
              <div>
                <span className="text-[#89bada] block text-[10px] font-medium">Temporal intersection</span>
                <span className="text-sm font-bold text-[#89bada]">T−16h (13:53 UTC)</span>
              </div>
              <div>
                <span className="text-[#89bada] block text-[10px] font-medium">Speed / Heading</span>
                <span className="font-semibold text-[#edf4fd]">
                  {topSuspect.sogKn} kn @ {topSuspect.cogDeg.toString().padStart(3, '0')}°
                </span>
              </div>
            </div>

            {/* Factor breakdown */}
            <div className="border-t border-[#1168a0]/50 pt-3.5">
              <div className="text-[10px] text-[#89bada] mb-2 font-bold uppercase tracking-wider">
                Score Contribution Breakdown:
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-[11px]">
                <div className="p-2.5 bg-[#0a1829] rounded-lg border border-[#1168a0]/60">
                  <span className="text-[#89bada] block text-[10px] font-medium">Spatial (45%)</span>
                  <span className="text-[#f1aa6f] font-bold">{topSuspect.spatialScore} pts</span>
                </div>
                <div className="p-2.5 bg-[#0a1829] rounded-lg border border-[#1168a0]/60">
                  <span className="text-[#89bada] block text-[10px] font-medium">Temporal (20%)</span>
                  <span className="text-[#89bada] font-bold">{topSuspect.temporalScore} pts</span>
                </div>
                <div className="p-2.5 bg-[#0a1829] rounded-lg border border-[#1168a0]/60">
                  <span className="text-[#89bada] block text-[10px] font-medium">Course (20%)</span>
                  <span className="text-[#edf4fd] font-bold">{topSuspect.courseScore} pts</span>
                </div>
                <div className="p-2.5 bg-[#0a1829] rounded-lg border border-[#1168a0]/60">
                  <span className="text-[#89bada] block text-[10px] font-medium">Speed (15%)</span>
                  <span className="text-[#f1aa6f] font-bold">{topSuspect.speedScore} pts</span>
                </div>
              </div>
            </div>
          </div>

          {/* Section 6: Candidate Vessels Attribution Ranking Table */}
          <div className="space-y-4">
            <div className="border-b border-[#1168a0]/40 pb-2 flex flex-col sm:flex-row sm:items-center justify-between gap-1">
              <h2 className="text-xs font-bold text-[#89bada] uppercase tracking-wider flex items-center gap-2">
                <ListOrdered className="w-3.5 h-3.5 text-[#f1aa6f]" />
                <span>CANDIDATE VESSELS ATTRIBUTION RANKING</span>
              </h2>
              <span className="text-[10px] text-[#89bada]">
                Ranked by multi-factor Bayesian attribution score
              </span>
            </div>

            <div className="overflow-x-auto rounded-xl border border-[#1168a0]/60 bg-[#082e49]/70 shadow-xl">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                  <tr className="bg-[#081524] text-[#89bada] border-b border-[#1168a0]/60 text-[10.5px] uppercase font-bold tracking-wider">
                    <th className="py-3 px-3.5">Rank</th>
                    <th className="py-3 px-3.5">Vessel Name & MMSI</th>
                    <th className="py-3 px-3.5">Vessel Type</th>
                    <th className="py-3 px-3.5">Closest Approach</th>
                    <th className="py-3 px-3.5">Temporal Intercept</th>
                    <th className="py-3 px-3.5">Speed / COG</th>
                    <th className="py-3 px-3.5">Attribution Score</th>
                    <th className="py-3 px-3.5 text-center">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#1168a0]/30 text-xs">
                  {suspects.map((s) => {
                    const isRank1 = s.rank === 1;
                    return (
                      <tr
                        key={s.mmsi}
                        className={`transition-colors ${
                          isRank1
                            ? 'bg-[#1168a0]/25 text-white font-medium border-l-4 border-[#f1aa6f]'
                            : 'hover:bg-white/[0.03] text-[#edf4fd]/90'
                        }`}
                      >
                        <td className="py-3 px-3.5 whitespace-nowrap">
                          <span
                            className={`inline-flex items-center justify-center w-6 h-6 rounded-full text-center text-[10.5px] font-bold ${
                              isRank1
                                ? 'bg-[#f1aa6f] text-[#0a3554] shadow-sm ring-2 ring-[#f1aa6f]/40'
                                : 'bg-[#0a1829] text-[#89bada] border border-[#1168a0]/60'
                            }`}
                          >
                            #{s.rank.toString().padStart(2, '0')}
                          </span>
                        </td>
                        <td className="py-3 px-3.5 whitespace-nowrap">
                          <div className="font-bold text-white flex items-center gap-1.5">
                            <Ship className={`w-3.5 h-3.5 ${isRank1 ? 'text-[#f1aa6f]' : 'text-[#89bada]'}`} />
                            <span>{s.vesselName}</span>
                          </div>
                          <span className="text-[10px] font-mono text-[#89bada]">
                            MMSI: {s.mmsi}
                          </span>
                        </td>
                        <td className="py-3 px-3.5 whitespace-nowrap text-[#edf4fd]">
                          {s.vesselType}
                        </td>
                        <td className="py-3 px-3.5 whitespace-nowrap">
                          <span className={`font-bold ${isRank1 ? 'text-[#f1aa6f]' : 'text-white'}`}>
                            {s.mdoKm.toFixed(2)} km
                          </span>
                        </td>
                        <td className="py-3 px-3.5 whitespace-nowrap font-mono text-[11px] text-[#89bada]">
                          T−{s.closestHourBack}h ({s.timeClosestApproach.slice(11, 16)} UTC)
                        </td>
                        <td className="py-3 px-3.5 whitespace-nowrap font-mono text-[11px] text-[#edf4fd]">
                          {s.sogKn} kn @ {s.cogDeg.toString().padStart(3, '0')}°
                        </td>
                        <td className="py-3 px-3.5 whitespace-nowrap">
                          <div className="flex items-center gap-2">
                            <div className="w-16 h-2 bg-[#081524] rounded-full overflow-hidden border border-[#1168a0]/40">
                              <div
                                className={`h-full rounded-full ${
                                  isRank1
                                    ? 'bg-gradient-to-r from-[#89bada] to-[#f1aa6f]'
                                    : 'bg-[#1168a0]'
                                }`}
                                style={{ width: `${s.culpritScorePct}%` }}
                              />
                            </div>
                            <span className={`font-bold text-xs ${isRank1 ? 'text-[#f1aa6f]' : 'text-[#89bada]'}`}>
                              {s.culpritScorePct}%
                            </span>
                          </div>
                        </td>
                        <td className="py-3 px-3.5 whitespace-nowrap text-center">
                          {isRank1 ? (
                            <span className="inline-block px-2.5 py-1 rounded-md bg-[#f1aa6f]/20 border border-[#f1aa6f]/60 text-[#f1aa6f] text-[10px] font-black uppercase tracking-wider shadow-xs">
                              Primary Culprit
                            </span>
                          ) : s.rank === 2 ? (
                            <span className="inline-block px-2 py-0.5 rounded-md bg-[#1168a0]/30 border border-[#1168a0]/60 text-[#89bada] text-[10px] font-semibold uppercase tracking-wider">
                              Low Probability
                            </span>
                          ) : (
                            <span className="inline-block px-2 py-0.5 rounded-md bg-white/5 border border-white/10 text-slate-400 text-[10px] font-medium uppercase tracking-wider">
                              Exonerated
                            </span>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
